#!/usr/bin/env ruby

require "xcodeproj"
require "fileutils"

root = File.expand_path("..", __dir__)

# Signing team: $DEVELOPMENT_TEAM, else Config/DevelopmentTeam.txt (git-ignored;
# see Config/DevelopmentTeam.example.txt), else none (simulator and unsigned
# builds still work).
team_file = File.join(root, "Config", "DevelopmentTeam.txt")
development_team = ENV["DEVELOPMENT_TEAM"].to_s.strip
if development_team.empty? && File.file?(team_file)
  development_team = File.readlines(team_file, chomp: true)
    .map(&:strip)
    .reject { |line| line.empty? || line.start_with?("#") }
    .first
    .to_s
end

# Every identifier derives from one prefix, so a fork can build under its own
# IDs: BUNDLE_ID_PREFIX=com.example.dc ruby scripts/generate_project.rb
bundle_id_prefix = ENV["BUNDLE_ID_PREFIX"].to_s.strip
bundle_id_prefix = "io.github.kccarlos.forumind" if bundle_id_prefix.empty?
unless bundle_id_prefix.match?(/\A[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)+\z/)
  abort "BUNDLE_ID_PREFIX must be a reverse-DNS identifier (got #{bundle_id_prefix.inspect})"
end
build_number = ENV["BUILD_NUMBER"].to_s.strip
build_number = "1" if build_number.empty?
marketing_version = "1.0.0"

# Settings every target shares. DC_APP_GROUP feeds the entitlements files;
# DC_IDENTIFIER_PREFIX feeds the Info.plist keys AppIdentity.swift reads.
identity_settings = {
  "DC_APP_GROUP" => "group.#{bundle_id_prefix}",
  "DC_IDENTIFIER_PREFIX" => bundle_id_prefix
}
identity_settings["DEVELOPMENT_TEAM"] = development_team unless development_team.empty?
project_path = File.join(root, "Forumind.xcodeproj")
FileUtils.rm_rf(project_path)

project = Xcodeproj::Project.new(project_path)
project.root_object.attributes["LastSwiftUpdateCheck"] = "2660"
project.root_object.attributes["LastUpgradeCheck"] = "2660"
# Localizations: English is the development language; the String Catalogs
# (*.xcstrings) hold Simplified and Traditional Chinese. With more than one
# localization in the bundle, iOS shows Settings › Forumind › Language.
# See docs/DEVELOPMENT.md#localization.
project.root_object.development_region = "en"
project.root_object.known_regions = %w[en Base zh-Hans zh-Hant]

app_group = project.main_group.new_group("Forumind", "Forumind")
test_group = project.main_group.new_group("ForumindTests", "ForumindTests")
ui_test_group = project.main_group.new_group(
  "ForumindUITests",
  "ForumindUITests"
)
share_group = project.main_group.new_group("ForumindShare", "ForumindShare")

app_target = project.new_target(:application, "Forumind", :ios, "17.0")
app_target.product_reference.name = "Forumind.app"

# Compiled into both the app and the share extension.
shared_source_names = [
  "AppIdentity.swift",
  "BrandMark.swift",
  "BrandMarkShapes.swift",
  "IncomingLink.swift"
]
shared_source_references = []

Dir.glob(File.join(root, "Forumind", "**", "*.swift")).sort.each do |path|
  relative_path = path.delete_prefix("#{root}/Forumind/")
  reference = app_group.new_file(relative_path)
  app_target.source_build_phase.add_file_reference(reference)
  shared_source_references << reference if shared_source_names.include?(relative_path)
end

assets = app_group.new_file("Assets.xcassets")
app_target.resources_build_phase.add_file_reference(assets)

# String Catalogs: UI strings, and the Info.plist strings (display name,
# usage descriptions). Kept in sync by scripts/i18n/sync-catalogs.sh.
%w[Localizable.xcstrings InfoPlist.xcstrings].each do |name|
  app_target.resources_build_phase.add_file_reference(app_group.new_file(name))
end

# Ad/tracker blocking rules (generated by scripts/adblock/update_rules.sh).
# A folder reference ("blue folder") copies the directory as-is, so the app
# finds it at Bundle.main's ContentBlocking/ subdirectory and chunk files can
# be added or removed without regenerating the project.
content_blocking = app_group.new_reference("ContentBlocking")
content_blocking.last_known_file_type = "folder"
app_target.resources_build_phase.add_file_reference(content_blocking)
app_group.new_file("Info.plist")
app_group.new_file("Forumind.entitlements")
# Privacy manifests (App Store requirement; see docs/APP_STORE.md).
app_privacy = app_group.new_file("PrivacyInfo.xcprivacy")
app_privacy.last_known_file_type = "text.xml"
app_target.resources_build_phase.add_file_reference(app_privacy)

def flag_value(name)
  value = ENV[name].to_s.strip
  return nil if value.empty?
  return true if %w[1 YES yes true].include?(value)
  return false if %w[0 NO no false].include?(value)
  abort "#{name} must be YES or NO (got #{value.inspect})"
end

# Capabilities beyond the base entitlements (App Group only).
#
# - CloudKit (iCloud sync): on whenever a team is resolved, because CloudKit
#   needs a signed build and an app without the iCloud entitlement crashes
#   on its first CloudKit call. DC_ENABLE_CLOUDKIT=YES|NO overrides.
#   Unsigned builds (CI, forks without a team, CODE_SIGNING_ALLOWED=NO) get
#   neither the entitlement nor `CLOUDKIT_ENABLED`, so sync stays off there.
# - Private Cloud Compute: a managed entitlement Apple assigns on request.
#   DC_ENABLE_PCC=YES. See docs/APPLE_INTELLIGENCE.md.
#
# The signing entitlements are composed from Forumind/Forumind.entitlements
# plus the enabled capabilities into Forumind/Generated/Forumind.entitlements
# (git-ignored). With nothing beyond the base (the committed project), the
# project signs with the committed base file directly.
cloudkit_override = flag_value("DC_ENABLE_CLOUDKIT")
cloudkit_enabled = cloudkit_override.nil? ? !development_team.empty? : cloudkit_override
pcc_enabled = flag_value("DC_ENABLE_PCC") || false
cloudkit_container = "iCloud.$(DC_IDENTIFIER_PREFIX)"

extra_entitlements = {}
if cloudkit_enabled
  # "development" here; exporting for TestFlight / the App Store re-signs
  # with the distribution profile, which switches it to "production".
  extra_entitlements["aps-environment"] = "development"
  extra_entitlements["com.apple.developer.icloud-container-identifiers"] = [cloudkit_container]
  extra_entitlements["com.apple.developer.icloud-services"] = ["CloudKit"]
end
extra_entitlements["com.apple.developer.private-cloud-compute"] = true if pcc_enabled

base_entitlements_path = "Forumind/Forumind.entitlements"
generated_entitlements_dir = File.join(root, "Forumind", "Generated")
FileUtils.rm_rf(generated_entitlements_dir)
app_entitlements_path =
  if extra_entitlements.empty?
    base_entitlements_path
  else
    entitlements = Xcodeproj::Plist.read_from_path(File.join(root, base_entitlements_path))
    entitlements.merge!(extra_entitlements)
    FileUtils.mkdir_p(generated_entitlements_dir)
    Xcodeproj::Plist.write_to_path(entitlements, File.join(generated_entitlements_dir, "Forumind.entitlements"))
    "Forumind/Generated/Forumind.entitlements"
  end

app_swift_flags = ["$(inherited)"]
app_swift_flags << "-D CLOUDKIT_ENABLED" if cloudkit_enabled
app_swift_flags << "-D PCC_ENABLED" if pcc_enabled

app_target.build_configurations.each do |configuration|
  settings = configuration.build_settings
  settings["ASSETCATALOG_COMPILER_APPICON_NAME"] = "AppIcon"
  settings["ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME"] = "AccentColor"
  settings["OTHER_SWIFT_FLAGS"] = app_swift_flags.join(" ")
  settings["CODE_SIGN_ENTITLEMENTS"] = app_entitlements_path
  settings["CODE_SIGN_STYLE"] = "Automatic"
  settings["CURRENT_PROJECT_VERSION"] = build_number
  settings.merge!(identity_settings)
  settings["GENERATE_INFOPLIST_FILE"] = "NO"
  settings["INFOPLIST_FILE"] = "Forumind/Info.plist"
  settings["IPHONEOS_DEPLOYMENT_TARGET"] = "17.0"
  settings["MARKETING_VERSION"] = marketing_version
  settings["PRODUCT_BUNDLE_IDENTIFIER"] = bundle_id_prefix
  settings["PRODUCT_NAME"] = "$(TARGET_NAME)"
  settings["SUPPORTED_PLATFORMS"] = "iphoneos iphonesimulator"
  settings["SUPPORTS_MACCATALYST"] = "NO"
  settings["SWIFT_EMIT_LOC_STRINGS"] = "YES"
  settings["SWIFT_STRICT_CONCURRENCY"] = "minimal"
  settings["SWIFT_VERSION"] = "5.0"
  settings["TARGETED_DEVICE_FAMILY"] = "1,2"
end

share_target = project.new_target(:app_extension, "ForumindShare", :ios, "17.0")
share_target.product_reference.name = "ForumindShare.appex"

Dir.glob(File.join(root, "ForumindShare", "**", "*.swift")).sort.each do |path|
  reference = share_group.new_file(path.delete_prefix("#{root}/ForumindShare/"))
  share_target.source_build_phase.add_file_reference(reference)
end
shared_source_references.each do |reference|
  share_target.source_build_phase.add_file_reference(reference)
end

Dir.glob(File.join(root, "ForumindShare", "**", "*.js")).sort.each do |path|
  reference = share_group.new_file(path.delete_prefix("#{root}/ForumindShare/"))
  share_target.resources_build_phase.add_file_reference(reference)
end
%w[Localizable.xcstrings InfoPlist.xcstrings].each do |name|
  share_target.resources_build_phase.add_file_reference(share_group.new_file(name))
end
share_group.new_file("Info.plist")
share_group.new_file("ForumindShare.entitlements")
share_privacy = share_group.new_file("PrivacyInfo.xcprivacy")
share_privacy.last_known_file_type = "text.xml"
share_target.resources_build_phase.add_file_reference(share_privacy)

share_target.build_configurations.each do |configuration|
  settings = configuration.build_settings
  settings["APPLICATION_EXTENSION_API_ONLY"] = "YES"
  settings["CODE_SIGN_ENTITLEMENTS"] = "ForumindShare/ForumindShare.entitlements"
  settings["CODE_SIGN_STYLE"] = "Automatic"
  settings["CURRENT_PROJECT_VERSION"] = build_number
  settings.merge!(identity_settings)
  settings["GENERATE_INFOPLIST_FILE"] = "NO"
  settings["INFOPLIST_FILE"] = "ForumindShare/Info.plist"
  settings["IPHONEOS_DEPLOYMENT_TARGET"] = "17.0"
  settings["LD_RUNPATH_SEARCH_PATHS"] = [
    "$(inherited)",
    "@executable_path/Frameworks",
    "@executable_path/../../Frameworks"
  ]
  settings["MARKETING_VERSION"] = marketing_version
  settings["PRODUCT_BUNDLE_IDENTIFIER"] = "#{bundle_id_prefix}.share"
  settings["PRODUCT_NAME"] = "$(TARGET_NAME)"
  settings["SKIP_INSTALL"] = "YES"
  settings["SUPPORTED_PLATFORMS"] = "iphoneos iphonesimulator"
  settings["SUPPORTS_MACCATALYST"] = "NO"
  settings["SWIFT_EMIT_LOC_STRINGS"] = "YES"
  settings["SWIFT_STRICT_CONCURRENCY"] = "minimal"
  settings["SWIFT_VERSION"] = "5.0"
  settings["TARGETED_DEVICE_FAMILY"] = "1,2"
end

app_target.add_dependency(share_target)
embed_extensions = app_target.new_copy_files_build_phase("Embed Foundation Extensions")
embed_extensions.dst_subfolder_spec = "13"
embed_extensions.dst_path = ""
embedded_share = embed_extensions.add_file_reference(share_target.product_reference, true)
embedded_share.settings = { "ATTRIBUTES" => ["RemoveHeadersOnCopy"] }

test_target = project.new_target(:unit_test_bundle, "ForumindTests", :ios, "17.0")
test_target.add_dependency(app_target)

Dir.glob(File.join(root, "ForumindTests", "**", "*.swift")).sort.each do |path|
  reference = test_group.new_file(path.delete_prefix("#{root}/ForumindTests/"))
  test_target.source_build_phase.add_file_reference(reference)
end

test_target.build_configurations.each do |configuration|
  settings = configuration.build_settings
  settings["BUNDLE_LOADER"] = "$(TEST_HOST)"
  settings["CODE_SIGN_STYLE"] = "Automatic"
  settings.merge!(identity_settings)
  settings["GENERATE_INFOPLIST_FILE"] = "YES"
  settings["IPHONEOS_DEPLOYMENT_TARGET"] = "17.0"
  settings["PRODUCT_BUNDLE_IDENTIFIER"] = "#{bundle_id_prefix}.tests"
  settings["SWIFT_STRICT_CONCURRENCY"] = "minimal"
  settings["SWIFT_VERSION"] = "5.0"
  settings["TARGETED_DEVICE_FAMILY"] = "1,2"
  settings["TEST_HOST"] = "$(BUILT_PRODUCTS_DIR)/Forumind.app/Forumind"
end

ui_test_target = project.new_target(
  :ui_test_bundle,
  "ForumindUITests",
  :ios,
  "17.0"
)
ui_test_target.add_dependency(app_target)

Dir.glob(File.join(root, "ForumindUITests", "**", "*.swift")).sort.each do |path|
  reference = ui_test_group.new_file(
    path.delete_prefix("#{root}/ForumindUITests/")
  )
  ui_test_target.source_build_phase.add_file_reference(reference)
end

ui_test_target.build_configurations.each do |configuration|
  settings = configuration.build_settings
  settings["CODE_SIGN_STYLE"] = "Automatic"
  settings.merge!(identity_settings)
  settings["GENERATE_INFOPLIST_FILE"] = "YES"
  settings["IPHONEOS_DEPLOYMENT_TARGET"] = "17.0"
  settings["PRODUCT_BUNDLE_IDENTIFIER"] = "#{bundle_id_prefix}.uitests"
  settings["SWIFT_STRICT_CONCURRENCY"] = "minimal"
  settings["SWIFT_VERSION"] = "5.0"
  settings["TARGETED_DEVICE_FAMILY"] = "1,2"
  settings["TEST_TARGET_NAME"] = "Forumind"
end

project.build_configurations.each do |configuration|
  settings = configuration.build_settings
  settings["CLANG_ENABLE_MODULES"] = "YES"
  settings["LOCALIZATION_PREFERS_STRING_CATALOGS"] = "YES"
  settings["SWIFT_VERSION"] = "5.0"
end

project.save

workspace_path = File.join(project_path, "project.xcworkspace")
FileUtils.mkdir_p(workspace_path)
File.write(
  File.join(workspace_path, "contents.xcworkspacedata"),
  <<~XML
    <?xml version="1.0" encoding="UTF-8"?>
    <Workspace
       version = "1.0">
       <FileRef
          location = "self:">
       </FileRef>
    </Workspace>
  XML
)

scheme = Xcodeproj::XCScheme.new
scheme.add_build_target(app_target)
scheme.add_test_target(test_target)
scheme.add_test_target(ui_test_target)
scheme.set_launch_target(app_target)
scheme.save_as(project_path, "Forumind", true)

capabilities = []
capabilities << "CloudKit" if cloudkit_enabled
capabilities << "PCC" if pcc_enabled
puts "Generated #{project_path}"
puts "Capabilities: #{capabilities.empty? ? "none (base entitlements)" : capabilities.join(", ")}; entitlements: #{app_entitlements_path}"
