import CryptoKit
import WebKit
import XCTest

/// Verifies the bundled ad/tracker blocking rules (generated by
/// scripts/adblock/update_rules.sh) against the manifest contract and compiles
/// every chunk with the real WebKit content-rule-list compiler.
@MainActor
final class ContentBlockingRulesTests: XCTestCase {
    private struct Manifest: Decodable {
        struct Source: Decodable {
            let name: String
            let url: String
            let listVersion: String
            let license: String
        }

        struct RuleList: Decodable {
            let identifier: String
            let category: String
            let file: String
            let ruleCount: Int
            let sha256: String
        }

        let version: String
        let generatedAt: String
        let sources: [Source]
        let lists: [RuleList]
    }

    private func loadManifest() throws -> (Manifest, URL) {
        let url = try XCTUnwrap(
            Bundle.main.url(forResource: "manifest", withExtension: "json", subdirectory: "ContentBlocking"),
            "ContentBlocking/manifest.json is missing from the app bundle"
        )
        let manifest = try JSONDecoder().decode(Manifest.self, from: Data(contentsOf: url))
        return (manifest, url.deletingLastPathComponent())
    }

    func testManifestMatchesBundledFiles() throws {
        let (manifest, directory) = try loadManifest()

        XCTAssertNotNil(
            manifest.version.range(of: #"^\d{4}-\d{2}-\d{2}-[0-9a-f]{7,}$"#, options: .regularExpression),
            "unexpected version format: \(manifest.version)"
        )
        XCTAssertNotNil(ISO8601DateFormatter().date(from: manifest.generatedAt))
        XCTAssertEqual(Set(manifest.sources.map(\.name)), ["EasyList", "EasyPrivacy"])
        XCTAssertTrue(manifest.sources.allSatisfy { $0.license == "CC BY-SA 3.0" })
        XCTAssertEqual(Set(manifest.lists.map(\.category)), ["ads", "privacy"])
        XCTAssertEqual(Set(manifest.lists.map(\.identifier)).count, manifest.lists.count)
        XCTAssertNotNil(Bundle.main.url(forResource: "ATTRIBUTION", withExtension: "md", subdirectory: "ContentBlocking"))

        for list in manifest.lists {
            XCTAssertTrue(list.identifier.hasPrefix(list.category + "-"), list.identifier)
            XCTAssertEqual(list.file, list.identifier + ".json")
            let data = try Data(contentsOf: directory.appendingPathComponent(list.file))
            let digest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
            XCTAssertEqual(digest, list.sha256, "sha256 mismatch for \(list.file)")
            let rules = try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [Any], list.file)
            XCTAssertEqual(rules.count, list.ruleCount, "ruleCount mismatch for \(list.file)")
            XCTAssertGreaterThan(list.ruleCount, 0)
            XCTAssertLessThanOrEqual(list.ruleCount, 50_000)
        }
    }

    func testEveryChunkCompilesInWebKit() async throws {
        let (manifest, directory) = try loadManifest()
        let storeURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("ContentBlockingRulesTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: storeURL, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: storeURL) }
        let store = try XCTUnwrap(WKContentRuleListStore(url: storeURL))

        var total: TimeInterval = 0
        for list in manifest.lists {
            let json = try String(contentsOf: directory.appendingPathComponent(list.file), encoding: .utf8)
            let start = Date()
            do {
                let compiled = try await store.compileContentRuleList(
                    forIdentifier: list.identifier,
                    encodedContentRuleList: json
                )
                XCTAssertNotNil(compiled, list.identifier)
            } catch {
                XCTFail("\(list.file) failed to compile: \(error)")
            }
            let elapsed = Date().timeIntervalSince(start)
            total += elapsed
            print(String(format: "[ContentBlocking] %@: %d rules compiled in %.2fs", list.identifier, list.ruleCount, elapsed))
        }
        print(String(format: "[ContentBlocking] %@: all %d lists compiled in %.2fs", manifest.version, manifest.lists.count, total))
    }
}
